version: '3'

services:
  weblama-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8081:8081"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - DEBUG=true
      - API_URL=http://apilama-mock:8080
    command: |
      bash -c "npm test"
    depends_on:
      - apilama-mock

  weblama-dev:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - DEBUG=true
      - API_URL=http://apilama-mock:8080
    command: |
      bash -c "npm start"
    depends_on:
      - apilama-mock

  apilama-mock:
    build:
      context: ../apilama
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    volumes:
      - ../apilama/tests:/app/tests
      - ../apilama/test-reports:/app/test-reports
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=true
      - MOCK_MODE=true
    command: |
      bash -c "python -m apilama.app --port 8080 --host 0.0.0.0 --mock"

volumes:
  test-reports:
